### ISSUE TITLE
Menu Item "Balances" broken in PROD

### ISSUE THREAD

**Issue by krico** [krico/jas#319]
This seems to be due to the deletion of an organization `Organization(1020001)`
```
    F 01:03:35.215 Uncaught exception from servlet
      java.io.IOException: com.google.appengine.repackaged.org.codehaus.jackson.map.JsonMappingException: No entity was found matching the key: Organization(1020001) (through reference chain: java.util.HashMap["items"]->java.util.ArrayList[5])
      	at com.google.api.server.spi.response.ServletResponseResultWriter.writeValueAsString(ServletResponseResultWriter.java:187)
      	at com.google.api.server.spi.response.ServletResponseResultWriter.write(ServletResponseResultWriter.java:74)
      	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:394)
      	at com.google.api.server.spi.SystemServiceServlet.execute(SystemServiceServlet.java:160)
      	at com.google.api.server.spi.SystemServiceServlet.doPost(SystemServiceServlet.java:118)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
      	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
      	at com.jasify.schedule.appengine.http.filter.UserContextFilter.doFilter(UserContextFilter.java:29)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
      	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
      	at java.lang.Thread.run(Thread.java:745)
      Caused by: com.google.appengine.repackaged.org.codehaus.jackson.map.JsonMappingException: No entity was found matching the key: Organization(1020001) (through reference chain: java.util.HashMap["items"]->java.util.ArrayList[5])
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:218)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.SerializerBase.wrapAndThrow(SerializerBase.java:166)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.serializeContents(StdContainerSerializers.java:127)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.serializeContents(StdContainerSerializers.java:71)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:86)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:262)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:610)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ObjectWriter._configAndWriteValue(ObjectWriter.java:456)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ObjectWriter.writeValueAsString(ObjectWriter.java:393)
      	at com.google.api.server.spi.response.ServletResponseResultWriter.writeValueAsString(ServletResponseResultWriter.java:183)
      	... 40 more
      Caused by: org.slim3.datastore.EntityNotFoundRuntimeException: No entity was found matching the key: Organization(1020001)
      	at org.slim3.datastore.AsyncDatastoreDelegate$1.wrap(AsyncDatastoreDelegate.java:579)
      	at org.slim3.datastore.AsyncDatastoreDelegate$1.wrap(AsyncDatastoreDelegate.java:568)
      	at com.google.appengine.api.utils.FutureWrapper.wrapAndCache(FutureWrapper.java:55)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
      	at org.slim3.util.FutureUtil.getQuietly(FutureUtil.java:78)
      	at org.slim3.datastore.DatastoreDelegate.get(DatastoreDelegate.java:1102)
      	at org.slim3.datastore.DatastoreDelegate.getWithoutTx(DatastoreDelegate.java:896)
      	at org.slim3.datastore.Datastore.getWithoutTx(Datastore.java:1114)
      	at org.slim3.datastore.ModelRef.refresh(ModelRef.java:142)
      	at org.slim3.datastore.ModelRef.getModel(ModelRef.java:72)
      	at com.jasify.schedule.appengine.util.FormatUtil.toString(FormatUtil.java:102)
      	at com.jasify.schedule.appengine.util.FormatUtil.toString(FormatUtil.java:110)
      	at com.jasify.schedule.appengine.spi.transform.JasAccountTransformer.transformTo(JasAccountTransformer.java:19)
      	at com.jasify.schedule.appengine.spi.transform.JasAccountTransformer.transformTo(JasAccountTransformer.java:13)
      	at com.google.api.server.spi.config.annotationreader.ApiAnnotationIntrospector$1.serialize(ApiAnnotationIntrospector.java:117)
      	at com.google.appengine.repackaged.org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.serializeContents(StdContainerSerializers.java:122)
      	... 50 more
```

**Comment by krico** [comment]
Deleted the bad stale account
