### ISSUE TITLE
Datastore contention causes booking failure

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#560]
I created a checkout of a large number of activities and activity packages. After successfully paying via PayPal I triggered the following exception.
```
SEVERE: exception occurred while calling backed method
java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again.
	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:48)
	at com.google.appengine.api.datastore.DatastoreApiHelper$AsyncCallWrapper.convertException(DatastoreApiHelper.java:74)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:96)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:75)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:35)
	at com.google.appengine.api.datastore.TransactionImpl.commit(TransactionImpl.java:124)
	at com.jasify.schedule.appengine.model.balance.DefaultBalanceService.applyTransferTransaction(DefaultBalanceService.java:365)
	at com.jasify.schedule.appengine.model.balance.DefaultBalanceService.applyTransfer(DefaultBalanceService.java:165)
	at com.jasify.schedule.appengine.model.balance.DefaultBalanceService.subscription(DefaultBalanceService.java:99)
	at com.jasify.schedule.appengine.model.balance.DefaultBalanceService.subscription(DefaultBalanceService.java:89)
	at com.jasify.schedule.appengine.model.balance.DefaultBalanceService.subscription(DefaultBalanceService.java:79)
	at com.jasify.schedule.appengine.model.payment.workflow.ActivityPaymentWorkflow.onCompleted(ActivityPaymentWorkflow.java:90)
	at com.jasify.schedule.appengine.model.payment.workflow.PaymentWorkflowEngine.transition(PaymentWorkflowEngine.java:64)
	at com.jasify.schedule.appengine.model.payment.DefaultPaymentService.transitionWorkflowList(DefaultPaymentService.java:85)
	at com.jasify.schedule.appengine.model.payment.DefaultPaymentService.executePayment(DefaultPaymentService.java:160)
	at com.jasify.schedule.appengine.spi.BalanceEndpoint.executePayment(BalanceEndpoint.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:130)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:359)
	at com.google.api.server.spi.SystemServiceServlet.execute(SystemServiceServlet.java:160)
	at com.google.api.server.spi.SystemServiceServlet.doPost(SystemServiceServlet.java:118)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.jasify.schedule.appengine.http.filter.UserContextFilter.doFilter(UserContextFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:491)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

Jun 28, 2015 9:52:08 PM com.google.appengine.tools.appstats.MemcacheWriter logMaybe
```

**Comment by krico** [comment]
For now you could enqueue the task in the queue with a 30 second delay.
