### ISSUE TITLE
Prod: Payment Cancellation task throws Exception

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#615]
User excited payment. Cancellation task queued and executed. Following exception was generated
```
18:41:13.695
200 60 B 3.54s /_ah/queue/__deferred__
0.1.0.2 - - [23/Jul/2015:09:41:13 -0700] "POST /_ah/queue/__deferred__ HTTP/1.1" 200 60 "https://jasify-schedule.appspot.com/_ah/spi/com.jasify.schedule.appengine.spi.BalanceEndpoint.createCheckoutPayment" "AppEngine-Google; (+http://code.google.com/appengine)" "jasify-schedule.appspot.com" ms=3540 cpu_ms=1892 cpm_usd=0.000132 queue_name=payment-queue task_name=0663745408253031852 instance=00c61b117cfb4e2a19db7fb673bb42369966559e app_engine_release=1.9.24
```
```
18:41:12.741
com.jasify.schedule.appengine.model.payment.task.CancelPaymentTask executePayment: Failed to complete payment
com.jasify.schedule.appengine.model.payment.PaymentException: com.paypal.base.rest.PayPalRESTException: Response Code : 400 with response : {"name":"PAYMENT_NOT_APPROVED_FOR_EXECUTION","message":"Payer has not approved payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#PAYMENT_NOT_APPROVED_FOR_EXECUTION","debug_id":"e94025fe628c8"}
	at com.jasify.schedule.appengine.model.payment.PayPalPaymentProvider$DefaultPayPalInterface.execute(PayPalPaymentProvider.java:417)
	at com.jasify.schedule.appengine.model.payment.PayPalPaymentProvider.executePayment(PayPalPaymentProvider.java:226)
	at com.jasify.schedule.appengine.model.payment.PayPalPaymentProvider.executePayment(PayPalPaymentProvider.java:34)
	at com.jasify.schedule.appengine.model.payment.DefaultPaymentService.executePayment(DefaultPaymentService.java:151)
	at com.jasify.schedule.appengine.model.payment.task.CancelPaymentTask.executePayment(CancelPaymentTask.java:53)
	at com.jasify.schedule.appengine.model.payment.task.CancelPaymentTask.run(CancelPaymentTask.java:30)
	at com.google.apphosting.utils.servlet.DeferredTaskServlet.performRequest(DeferredTaskServlet.java:142)
	at com.google.apphosting.utils.servlet.DeferredTaskServlet.service(DeferredTaskServlet.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.jasify.schedule.appengine.http.filter.UserContextFilter.doFilter(UserContextFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:482)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.paypal.base.rest.PayPalRESTException: Response Code : 400 with response : {"name":"PAYMENT_NOT_APPROVED_FOR_EXECUTION","message":"Payer has not approved payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#PAYMENT_NOT_APPROVED_FOR_EXECUTION","debug_id":"e94025fe628c8"}
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:412)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:261)
	at com.paypal.api.payments.Payment.execute(Payment.java:402)
	at com.paypal.api.payments.Payment.execute(Payment.java:368)
	at com.jasify.schedule.appengine.model.payment.PayPalPaymentProvider$DefaultPayPalInterface.execute(PayPalPaymentProvider.java:415)
	... 44 more
Caused by: com.paypal.base.exception.ClientActionRequiredException: Response Code : 400 with response : {"name":"PAYMENT_NOT_APPROVED_FOR_EXECUTION","message":"Payer has not approved payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#PAYMENT_NOT_APPROVED_FOR_EXECUTION","debug_id":"e94025fe628c8"}
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:105)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:403)
	... 48 more
```

**Comment by krico** [comment]
I guess she stopped on PayPal and never came back... Did we try to execute
without PayerID?

**Comment by wszarmach** [comment]
I think we tried to find the state of the payment using the PayerID.
