### ISSUE TITLE
PROD: Checkout Payment concurrent modification exception

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#616]
User reported that items selected from a previous session close to a month ago were still in the shopping cart. This exception may be related to old and new activities.
```
2015-07-23 18:11:08.842  500     257 B   987ms E 18:11:08.834 /_ah/spi/com.jasify.schedule.appengine.spi.BalanceEndpoint.createCheckoutPayment
  77.57.113.90 - - [23/Jul/2015:09:11:08 -0700] "POST /_ah/spi/com.jasify.schedule.appengine.spi.BalanceEndpoint.createCheckoutPayment HTTP/1.1" 500 257 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36" "jasify-schedule.appspot.com" ms=987 cpu_ms=176 cpm_usd=0.000268 instance=00c61b117cfb4e2a19db7fb673bb42369966559e app_engine_release=1.9.24
```
```
18:11:08.834 com.google.api.server.spi.SystemService invokeServiceMethod: exception occurred while calling backed method
      java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again.
      	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:57)
      	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:127)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:96)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
      	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
      	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76)
      	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36)
      	at com.google.appengine.api.datastore.TransactionImpl.commit(TransactionImpl.java:124)
      	at com.jasify.schedule.appengine.model.payment.DefaultPaymentService.createPayment(DefaultPaymentService.java:125)
      	at com.jasify.schedule.appengine.spi.BalanceEndpoint.createPaymentInternal(BalanceEndpoint.java:145)
      	at com.jasify.schedule.appengine.spi.BalanceEndpoint.createCheckoutPayment(BalanceEndpoint.java:100)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:45)
      	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:359)
      	at com.google.api.server.spi.SystemServiceServlet.execute(SystemServiceServlet.java:160)
      	at com.google.api.server.spi.SystemServiceServlet.doPost(SystemServiceServlet.java:118)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
      	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
      	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.jasify.schedule.appengine.http.filter.UserContextFilter.doFilter(UserContextFilter.java:29)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	at java.lang.Thread.run(Thread.java:745)
```

**Comment by krico** [comment]
I thought we wrapped this with TransactionOperator

**Comment by wszarmach** [comment]
Seems its been missed
